# 异常处理
> 程序执行中产生的错误被称为异常，Python 用异常对象（Exception Object）来表示异常情况。遇到错误后会引发异常，如果异常对象未被处理或捕获，程序就会用回溯（TraceBack，一种错误信息）终止执行。
## 异常捕捉
使用`try/except:`复合语句来实现异常的捕捉。
1. 异常捕获与处理的一般格式
    ``` python
    try:
        <statement_1>
    except <name_1>:            # 捕获异常 name_1
        <statement_2>
    except (name_2,name_3):     # 捕获异常 name_2
        <statement_3>
    except <name_4> as e:       # 捕获异常 name_4，e 作为其实例
        <statement_4>
    except:                     # 捕获其他所有异常
        <statement_5>
    else:                       # 无异常
        <statement_6>
    finally:                    # 不管是否发生异常，保证执行
        <statement_7>

    ```
    检测到<statement>里的错误，python引发异常，跳到try的异常处理器，而后继续之后的语句。如果异常没有被相应的`except`处理，python的默认异常处理行为将启动。
    
2. 按异常类名捕获异常

    python内置很多异常类`ValueError`、`ZeroDivisonError`、`OverFlowError`等。

3. 使用异常实例  
    ```python
    except (ValueError,ZeroDivisionError) as e:
    print(e)
    ```
4. 捕获所有异常
    ```python
    except:
       <...>
    except Exception as e:
    
    ```
    同样会捕捉`Ctrl+C`，会隐藏未想到且未做好准备处理的错误。
## 自定义异常类
1. 自定义异常 形式如下
    ```python
    class SomeCustomException(Exception):
       pass
    ```
    - `SomeCustomExceptin`为自定义异常的名称
    - `Exception`未自定义异常所继承的积累
    - `pass`表示现在什么也不用做，因为所要执行的操作在`except`后
2. 抛出异常
    `raise <class>` 创建并抛出类的实例
    `raise <instance>` 抛出类的实例
    
3. `assert`语句（断言）
    可以视为条件式的raise语句
    
    形式：`assert<test>,<data>`    <data>可选
    
    效果类似：
    ```python
       if not <test>:
           raise AssertionError(<data>)
    ```